{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "matrix.fullname" . }}-synapse-config
  namespace: matrix
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: {{ include "matrix.fullname" . }}-synapse-config
    template:
      engineVersion: v2
      templateFrom:
      - configMap:
          # name of the configmap to pull in
          name: {{ include "matrix.fullname" . }}-synapse-config-tpl
          # here you define the keys that should be used as template
          items:
          - key: homeserver.yaml
  data:
  - secretKey: postgres_user
    remoteRef:
      key: matrix/postgres
      property: user
  - secretKey: postgres_password
    remoteRef:
      key: matrix/postgres
      property: password
  - secretKey: postgres_database
    remoteRef:
      key: matrix/postgres
      property: database
  - secretKey: postgres_host
    remoteRef:
      key: matrix/postgres
      property: host
  - secretKey: postgres_port
    remoteRef:
      key: matrix/postgres
      property: port
  - secretKey: redis_host
    remoteRef:
      key: matrix/redis
      property: host
  - secretKey: redis_port
    remoteRef:
      key: matrix/redis
      property: port
  - secretKey: redis_password
    remoteRef:
      key: matrix/redis
      property: password
  - secretKey: redis_database
    remoteRef:
      key: matrix/redis
      property: database
  - secretKey: oidc_client_id
    remoteRef:
      key: matrix/oidc
      property: client_id
  - secretKey: oidc_client_secret
    remoteRef:
      key: matrix/oidc
      property: client_secret
  - secretKey: oidc_issuer
    remoteRef:
      key: matrix/oidc
      property: issuer
  - secretKey: oidc_localpart_template
    remoteRef:
      key: matrix/oidc
      property: localpart_template
  - secretKey: oidc_display_name_template
    remoteRef:
      key: matrix/oidc
      property: display_name_template
  - secretKey: s3_endpoint
    remoteRef:
      key: matrix/s3
      property: endpoint
  - secretKey: s3_access_key
    remoteRef:
      key: matrix/s3
      property: access_key_id
  - secretKey: s3_secret_key
    remoteRef:
      key: matrix/s3
      property: secret_access_key
{{- end -}}
