apiVersion: v2
name: matrix
description: A helm chart for Matrix homeserver, element web-client, Jitsi conference and other components. This repo uses the [helm chart](https://github.com/typokign/matrix-chart) developed by @typokign as a basis.
icon: "https://matrix.org/images/matrix-logo-white.svg"
home: "https://github.com/Alpacked/matrix-helm"
sources:
  - "https://github.com/dacruz21/matrix-chart"
  - "https://github.com/Alpacked/matrix-helm"

type: application
version: 2.9.0
appVersion: 1.23.0

maintainers:
  - name: "David Cruz"
    email: "david@typokign.com"
    url: "https://github.com/typokign/"
  - name: "Yevhenii Hordashnyk"
    email: "yevhenii@alpacked.io"
    url: "https://github.com/jradikk/"
  - name: "Volodymyr Starodubov"
    email: "volodymyr.starodubov@alpacked.io"
    url: "https://github.com/v-starodubov/"

dependencies:
  - name: jitsi-meet
    version: 1.3.8
    repository: https://jitsi-contrib.github.io/jitsi-helm
    condition: jitsi-meet.enabled
  - name: postgresql
    version: 13.2.0
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 18.2.0
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
