apiVersion: v2
name: matrix
description: A Helm chart to deploy a Matrix homeserver stack into Kubernetes
icon: "https://matrix.org/images/matrix-logo-white.svg"
home: "https://github.com/Alpacked/matrix-helm"
sources:
  - "https://github.com/dacruz21/matrix-chart"
  - "https://github.com/Alpacked/matrix-helm"

type: application
version: 2.9.0
appVersion: 1.23.0

maintainers:
  - name: "David Cruz"
    email: "david@typokign.com"
    url: "https://github.com/typokign/"
  - name: "Yevhenii Hordashnyk"
    email: "yevhenii@alpacked.io"
    url: "https://github.com/jradikk/"
  - name: "Volodymyr Starodubov"
    email: "volodymyr.starodubov@alpacked.io"
    url: "https://github.com/v-starodubov/"

dependencies:
  - name: postgresql
    version: 13.2.0
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 18.2.0
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
