{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "matrix.fullname" . }}-postgresql-initdb
  labels:
  {{ include "matrix.labels" . | nindent 4}}
data:
  {{- if .Values.bridges.irc.enabled }}
  zzz_irc.sql: |
    CREATE DATABASE {{ .Values.bridges.irc.database }}
       ENCODING 'UTF8'
       LC_COLLATE='C'
       LC_CTYPE='C'
       template=template0
       OWNER {{ .Values.postgresql.auth.username }};
  {{- end }}
{{- end }}
