{{- if .Values.matrix.uvs.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "matrix.fullname" . }}-prosody-uvs
  labels:
{{ include "matrix.labels" . | indent 4 }}
{{ include "matrix.uvs.labels" . | indent 4}}
type: Opaque
stringData:
  MATRIX_UVS_ISSUER: "issuer"
  MATRIX_UVS_SYNC_POWER_LEVELS: "true"
  MATRIX_UVS_URL: "http://{{ include "matrix.fullname" . }}-uvs.{{ .Release.Namespace }}.svc.cluster.local:{{ default 3000 .Values.matrix.uvs.service.port}}"
  MATRIX_UVS_AUTH_TOKEN: {{ include "matrix.uvs.authToken" . }}
  MATRIX_UVS_ACCESS_TOKEN: {{ .Values.matrix.uvs.accessToken | quote }}
{{- end }}
