{{- if .Values.matrix.uvs.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "matrix.fullname" . }}-uvs
  labels:
{{ include "matrix.labels" . | indent 4 }}
{{ include "matrix.uvs.labels" . | indent 4}}
spec:
  type: {{ .Values.matrix.uvs.service.type }}
  ports:
    - port: {{ .Values.matrix.uvs.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "matrix.name" . }}-synapse
{{- end }}
