name: Docker Build and Scan Image

on:
  push:
    tags: [ "*" ]
    branches:
      - 'master'
      - 'feature/github-action-build-scan'

env:
  PLATFORMS: linux/amd64,linux/arm64

jobs:
  build:
    runs-on: ubuntu-latest
    environment: matrix-synapse
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Docker
        id: meta
        uses: ./.github/actions/configure-docker
        with:
          image_name: ${{ vars.IMAGE_NAME }}
          registry_username: ${{ secrets.DOCKERHUB_USERNAME }}
          registry_token: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ vars.CONTEXT }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: ${{ env.PLATFORMS }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  scan:
    needs: build
    runs-on: ubuntu-latest
    environment: matrix-synapse
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Docker
        id: meta
        uses: ./.github/actions/configure-docker
        with:
          image_name: ${{ vars.IMAGE_NAME }}
          registry_username: ${{ secrets.DOCKERHUB_USERNAME }}
          registry_token: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Load Docker image
        uses: docker/build-push-action@v5
        with:
          load: true
          context: ${{ vars.CONTEXT }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: ${{ env.PLATFORMS }}
          cache-from: type=gha

      - name: Scan Docker image for vulnerabilities
        id: container-scan
        uses: crazy-max/ghaction-container-scan@v3
        with:
          image: ${{ steps.meta.outputs.tags }}
          dockerfile: ${{ vars.CONTEXT }}/Dockerfile
          severity_threshold: HIGH
          annotations: true

      - name: Upload SARIF file
        if: ${{ steps.scan.outputs.sarif != '' }}
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.container-scan.outputs.sarif }}

  push:
    needs: scan
    runs-on: ubuntu-latest
    environment: matrix-synapse
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Docker
        id: meta
        uses: ./.github/actions/configure-docker
        with:
          image_name: ${{ vars.IMAGE_NAME }}
          registry_username: ${{ secrets.DOCKERHUB_USERNAME }}
          registry_token: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ${{ vars.CONTEXT }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: ${{ env.PLATFORMS }}
          cache-from: type=gha
